$(function(){function r(){var a="N\u00e3o solicitado";if($("#nome").length&&(a=$.trim($("#nome").val()),5>a.length))return $("#nome").addClass("fieldError"),$("#nome").keypress(function(d){$(d.currentTarget).removeClass("fieldError");$("#lblMsg").length&&$("#lblMsg").html("")}),$("#lblMsg").length?$("#lblMsg").html("Por favor, digite seu nome completo."):alert("Por favor, digite seu nome completo."),$("#nome").focus(),!1;var b="";if($("#email").length){b=$.trim($("#email").val());if(5>b.length)return $("#email").addClass("fieldError"),
$("#email").keypress(function(d){$(d.currentTarget).removeClass("fieldError");$("#lblMsg").length&&$("#lblMsg").html("")}),$("#lblMsg").length?$("#lblMsg").html("Por favor, digite seu email."):alert("Por favor, digite seu email."),$("#email").focus(),!1;if(!t(b))return $("#email").addClass("fieldError"),$("#email").keypress(function(d){$(d.currentTarget).removeClass("fieldError");$("#lblMsg").length&&$("#lblMsg").html("")}),$("#lblMsg").length?$("#lblMsg").html("Email inv\u00e1lido."):alert("Email inv\u00e1lido."),
$("#email").focus(),!1}var c="";if($("#telefone").length&&(c=$("#telefone").val(),14>c.length))return $("#telefone").addClass("fieldError"),$("#telefone").keypress(function(d){$(d.currentTarget).removeClass("fieldError");$("#lblMsg").length&&$("#lblMsg").html("")}),$("#lblMsg").length?$("#lblMsg").html("Por favor, digite o seu telefone."):alert("Por favor, digite o seu telefone."),$("#telefone").focus(),!1;var f="";if($("#celular").length&&(f=$("#celular").val(),14>f.length))return $("#celular").addClass("fieldError"),
$("#celular").keypress(function(d){$(d.currentTarget).removeClass("fieldError");$("#lblMsg").length&&$("#lblMsg").html("")}),$("#lblMsg").length?$("#lblMsg").html("Por favor, digite o seu celular."):alert("Por favor, digite o seu celular."),$("#celular").focus(),!1;var l="";if($("#polo").length&&(l=$("#polo").val(),2>l.length))return $("#polo").addClass("fieldError"),$("#polo").keypress(function(d){$(d.currentTarget).removeClass("fieldError");$("#lblMsg").length&&$("#lblMsg").html("")}),$("#lblMsg").length?
$("#lblMsg").html("Por favor, informe o seu polo."):alert("Por favor, informe o seu polo."),$("#polo").focus(),!1;var p="";if($("#estado").length&&(p=$("#estado").val(),2>p.length))return $("#estado").addClass("fieldError"),$("#estado").click(function(d){$(d.currentTarget).removeClass("fieldError");$("#lblMsg").length&&$("#lblMsg").html("")}),$("#lblMsg").length?$("#lblMsg").html("Por favor, escolha o seu estado."):alert("Por favor, escolha o seu estado."),$("#estado").focus(),!1;var q="";if($("#cidade").length&&
(q=$("#cidade").val(),1>q.length))return $("#cidade").addClass("fieldError"),$("#cidade").click(function(d){$(d.currentTarget).removeClass("fieldError");$("#lblMsg").length&&$("#lblMsg").html("")}),$("#lblMsg").length?$("#lblMsg").html("Por favor, escolha a sua cidade."):alert("Por favor, escolha a sua cidade."),$("#cidade").focus(),!1;var k="";if($("#mensagem").length){k=$("#mensagem").val();var g=$("#mensagem").attr("placeholder");if(g&&0<g.indexOf("*")&&1>k.length)return $("#mensagem").addClass("fieldError"),
$("#mensagem").click(function(d){$(d.currentTarget).removeClass("fieldError");$("#lblMsg").length&&$("#lblMsg").html("")}),$("#lblMsg").length?$("#lblMsg").html("Por favor, informe um valor"):alert("Por favor, informe um valor"),$("#mensagem").focus(),!1}if($("#extra").length){var e=$("#extra").val();if((g=$("#extra").attr("placeholder"))&&0<g.indexOf("*")&&1>e.length)return $("#extra").addClass("fieldError"),$("#extra").click(function(d){$(d.currentTarget).removeClass("fieldError");$("#lblMsg").length&&
$("#lblMsg").html("")}),$("#lblMsg").length?$("#lblMsg").html("Por favor, informe um valor"):alert("Por favor, informe um valor"),$("#extra").focus(),!1;e&&(k=k?k+(" - "+e):e)}if($("#senha").length&&$("#senha2").length&&$("#senha").val()!=$("#senha2").val())return $("#senha, #senha2").addClass("fieldError"),$("#senha, #senha2").click(function(d){$(d.currentTarget).removeClass("fieldError");$("#lblMsg").length&&$("#lblMsg").html("")}),$("#lblMsg").length?$("#lblMsg").html("Senhas n\u00e3o s\u00e3o iguais"):
alert("Senhas n\u00e3o s\u00e3o iguais"),$("#senha").focus(),!1;if($("#cpf").length&&(e=$("#cpf").val(),(g=$("#cpf").attr("placeholder"))&&0<g.indexOf("*")&&!u(e)))return $("#cpf").addClass("fieldError"),$("#cpf").click(function(d){$(d.currentTarget).removeClass("fieldError");$("#lblMsg").length&&$("#lblMsg").html("")}),$("#lblMsg").length?$("#lblMsg").html("Por favor, informe um CPF v\u00e1lido"):alert("Por favor, informe um CPF v\u00e1lido"),$("#cpf").focus(),!1;if($("#select-tema").length){if(e=
$("#select-tema").val())(g=!isNaN(parseFloat(e))&&isFinite(e))&&(e=$("#select-tema option:selected").text());else return $("#select-tema").addClass("fieldError"),$("#select-tema").click(function(d){$(d.currentTarget).removeClass("fieldError");$("#lblMsg").length&&$("#lblMsg").html("")}),$("#lblMsg").length?$("#lblMsg").html("Por favor, informe um valor"):alert("Por favor, informe um valor"),$("#select-tema").focus(),!1;k+=" Tema: "+e}if($("#select-categoria").length){if(e=$("#select-categoria").val())(g=
!isNaN(parseFloat(e))&&isFinite(e))&&(e=$("#select-categoria option:selected").text());else return $("#select-categoria").addClass("fieldError"),$("#select-categoria").click(function(d){$(d.currentTarget).removeClass("fieldError");$("#lblMsg").length&&$("#lblMsg").html("")}),$("#lblMsg").length?$("#lblMsg").html("Por favor, informe um valor"):alert("Por favor, informe um valor"),$("#select-categoria").focus(),!1;k+=" Categoria: "+e}if($("#select-curso").length){idSelectCurso=$("#select-curso").val();
if(!idSelectCurso)return $("#select-curso").addClass("fieldError"),$("#select-curso").click(function(d){$(d.currentTarget).removeClass("fieldError");$("#lblMsg").length&&$("#lblMsg").html("")}),$("#lblMsg").length?$("#lblMsg").html("Por favor, informe um valor"):alert("Por favor, informe um valor"),$("#select-curso").focus(),!1;k+=" Curso: "+$("#select-curso option:selected").text()+" ?courseId="+idSelectCurso+"&"}k+=" URL: "+document.location;k=$.trim(k);g=document.getElementsByClassName("form-check-input");
e=0;for(var v=g.length;e<v;e++)if(0==g[e].checked)return $("#lblMsg").length?$("#lblMsg").html('Favor concordar com "'+$(g[e]).data("alert")+'"'):alert('Favor concordar com "'+$(g[e]).data("alert")+'"'),$("#formacao").focus(),$(g[e]).focus(),!1;h.push(a);h.push(b);h.push(c);h.push(f);h.push(l);h.push(p);h.push(q);h.push(k);h.push(idSolucao);return!0}function u(a){if(""==a)return!1;a=a.replace(".","");a=a.replace(".","");for(a=a.replace("-","");11>a.length;)a="0"+a;if("11111111111"==a||"22222222222"==
a||"33333333333"==a||"44444444444"==a||"55555555555"==a||"66666666666"==a||"77777777777"==a||"88888888888"==a||"99999999999"==a||"00000000000"==a)return!1;var b=/^0+$|^1+$|^2+$|^3+$|^4+$|^5+$|^6+$|^7+$|^8+$|^9+$/,c=[],f=new Number,l=11;for(i=0;11>i;i++)c[i]=a.charAt(i),9>i&&(f+=c[i]*--l);2>(x=f%11)?c[9]=0:c[9]=11-x;f=0;l=11;for(y=0;10>y;y++)f+=c[y]*l--;2>(x=f%11)?c[10]=0:c[10]=11-x;return a.charAt(9)!=c[9]||a.charAt(10)!=c[10]||a.match(b)?!1:!0}function t(a){var b=new RegExp(/^[A-Za-z0-9_\-\.]+@[A-Za-z0-9_\-\.]{2,}\.[A-Za-z0-9]{2,}(\.[A-Za-z0-9])?/);
if("string"==typeof a){if(b.test(a))return!0}else if("object"==typeof a){if(b.test(a.value))return!0}else return!1}function m(a,b){b?(a.removeClass("input-loader"),a.prop("readonly",!1),a.removeAttr("disabled")):(a.addClass("input-loader"),a.prop("readonly",!0),a.attr("disabled","disabled"))}function n(a,b){if(!a){var c=RegExp("[?&]"+b+"=([^&]*)").exec(window.location.search);return c&&decodeURIComponent(c[1].replace(/\+/g," "))}a=a.toLowerCase();b=b.toLowerCase();if(-1<a.indexOf(b+"=")){c=a.split("?")[1].split("&");
for(var f=0;f<c.length;f++)if(0==c[f].indexOf(b+"="))return c=c[f].split("=")[1],-1<c.indexOf("#")&&(c=c.split("#")[0]),c}return""}function w(a){var b=(new Date).getTime()+7776E6;return{value:a,expiryDate:b}}var h;idSolucao="64741";idNegocio="3";getId="1";idSelectCurso=callBack="";$(document).on("click","#btnEnviarLead2",function(a){m($("#btnEnviarLead2"),!1);h=[];r()?(a=encodeURIComponent(JSON.stringify(h)),$.ajax({type:"POST",url:"https://euestudo.com.vc/online/cs/html5/ConectorSQL.aspx",data:{idNegocio:idNegocio,
request:8,getId:getId,IdSQL:684,SQLtype:"Ins",type:2,Param:a,Extra:""},dataType:"xml",beforeSend:function(){$("#imgLoading").length&&$("#imgLoading").show()},error:function(b){console.log(b);m($("#btnEnviarLead2"),!0)},success:function(b){var c=$(b).find("errors").children("total").text();(c=parseInt(c))?(b=$(b).find("errors").children("error").text(),$("#lblMsg").length?$("#lblMsg").html(b):alert(b)):($("#nome").length&&$("#nome").val(""),$("#email").length&&$("#email").val(""),$("#telefone").length&&
$("#telefone").val(""),$("#celular").length&&$("#celular").val(""),$("#polo").length&&$("#polo").val(""),$("#estado").length&&$("#estado").val(""),$("#cidade").length&&$("#cidade").val(""),$("#mensagem").length&&$("#mensagem").val(""),$("#lblMsg").length?($("#lblMsg").html("Informa\u00e7\u00f5es enviados com sucesso! Por favor, aguarde nosso contato."),$("#lblMsg").css("color","#ff9d05")):alert("Informa\u00e7\u00f5es enviados com sucesso! Por favor, aguarde nosso contato."));$("#imgLoading").length&&
$("#imgLoading").hide();m($("#btnEnviarLead2"),!0)}})):m($("#btnEnviarLead2"),!0)});$(document).on("click","#btnEnviarLead",function(a){m($("#btnEnviarLead"),!1);h=[];r()?(a=encodeURIComponent(JSON.stringify(h)),$.ajax({type:"POST",url:"https://euestudo.com.vc/online/cs/html5/ConectorSQL.aspx",data:{idNegocio:idNegocio,request:8,getId:getId,IdSQL:684,SQLtype:"Ins",type:2,Param:a,Extra:""},dataType:"xml",beforeSend:function(){$("#imgLoading").length&&$("#imgLoading").show()},error:function(b){console.log(b);
m($("#btnEnviarLead"),!0)},success:function(b){var c=$(b).find("errors").children("total").text();if(c=parseInt(c))b=$(b).find("errors").children("error").text(),$("#lblMsg").length?$("#lblMsg").html(b):alert(b);else{b=$(b).find("root").children("idnew").text();if(callBack){"function"===typeof callBack?callBack(b):(new Function(callBack+"("+b+")"))();return}if(idSelectCurso){window.location.href="/api/Comprar.aspx?id="+idSelectCurso+"&idMetadata="+b+"&txtNome="+$("#nome").val()+"&txtEmail="+$("#email").val()+
"&txtTelefone="+$("#celular").val()+"&txtEstado="+$("#estado").val()+"&txtCidade="+$("#cidade").val();return}$("#nome").length&&$("#nome").val("");$("#email").length&&$("#email").val("");$("#telefone").length&&$("#telefone").val("");$("#celular").length&&$("#celular").val("");$("#polo").length&&$("#polo").val("");$("#estado").length&&$("#estado").val("");$("#cidade").length&&$("#cidade").val("");$("#mensagem").length&&$("#mensagem").val("");$("#lblMsg").length?($("#lblMsg").html("Informa\u00e7\u00f5es enviados com sucesso! Por favor, aguarde nosso contato."),
$("#lblMsg").css("color","#ff9d05")):alert("Informa\u00e7\u00f5es enviados com sucesso! Por favor, aguarde nosso contato.")}$("#imgLoading").length&&$("#imgLoading").hide();m($("#btnEnviarLead"),!0)}})):m($("#btnEnviarLead"),!0)});(function(){var a=window.location.href,b=n(a,"gclid");b||parent===window||(a=document.referrer,b=n(a,"gclid"));var c=null,f;a=window.location.href;a=n(a,"gclsrc");a||parent===window||(a=document.referrer,a=n(a,"gclsrc"));a=!a||-1!==a.indexOf("aw");["gclid_field","foobar"].forEach(function(l){document.getElementById(l)&&
(f=document.getElementById(l))});b&&a&&(c=w(b),localStorage.setItem("gclid",JSON.stringify(c)));return(b=c||JSON.parse(localStorage.getItem("gclid")))&&(new Date).getTime()<b.expiryDate?(f&&(f.value=b.value),b.value):null})()});
